title: My School Life
author: Subhranil Banerjee
email: subhranil1807@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hi friends my name is Subhranil Banerjee. Welcome to this site.
I will tell about my journey in my school. So come to this site now.
# social links
twitter_username: subhranil1807
github_username:  subhranil0663
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
